version: '3'

services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend

  frontend:
    image: "node-22"
    user: "node"
    working_dir: home/node/app
    environment:
      - NODE_ENV=development
      - WDS_SOKET_PORT=0
    volumes:
      - ./frontend/:home/node/app
    expose:
      - 3000
    command: "yarn start"

  backend:
    image: todo-app/backend
    build: ./backend
    volumes:
      - ./backend/:user/src/app
    expose:
      - 30001
    command: "python src/server.py"
    environment:
      - debug=true
    env_file:
      - path: ./.env
        required: true
